#!/bin/bash
# This file is called by systemd via delcom@.service
#
# delcom-clock Copyright 2014 Stuart Pook http://www.pook.it/

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# https://github.com/stuart12/delcom-clock

# I have 3 clocks and I want them to show different things.  I use the
# kernel device to distinguish between the different clocks.

# You don;t need this script if you want all you clocks to show the same thing.
# Just call delcom-clock directly from delcom@.service

if [[ "$1" =~ /[0-9]+-[0-9]+\.[0-9]+:1\.0$ ]]
then
	: in a hub
	format='%m%d %k%M'
	update=60
	case "$1" in
	*.3:1.0)
		: in position 3 in a hub
		args="--control /run/led-bedroom --chown stuart"
		decimals=10000101
		;;
	*)
		decimals=10000100
		;;
	esac
else
	: not in a hub
	decimals=00010100
	format='%w %H%M%S'
	update=1
fi

exec /usr/local/lib/delcom-clock --syslog --decimals $decimals --update $update --format "$format" $args -- "$1"
