#!/bin/bash
# 17 May 2014, Copyright 2014 Stuart Pook http://www.pook.it/

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# https://github.com/stuart12/delcom-clock

# I have 3 clocks and I want them to show different things.  I use the
# kernel device to distinguish between the different clocks.

if [[ "$1" =~ [0-9]+\.[0-9]+: ]]
then
	: in a hub
	format='%m%d %k%M'
	update="--update 60"
	case "$1" in
	*.3:*)

		: in position 3 in a hub
		args="--control /run/led-bedroom --chown stuart"
		decimals=10000101
		;;
	*)
		decimals=10000100
		;;
	esac
else
	: not in a hub
	decimals=00010100
	format='%w %H%M%S'
fi

# systemd replaces the - in the kernel device with a /, put the dash back

exec /usr/local/lib/delcom-clock --syslog --decimals $decimals $update --format "$format" $args ${1/\//-}
